// Code generated by protoc-gen-go. DO NOT EDIT.
// source: summary/summary.proto

package summary

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Job struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Worker               string   `protobuf:"bytes,4,opt,name=worker,proto3" json:"worker,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_summary_741b49c5a0045d04, []int{0}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Job) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Job) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

type JobUpdate struct {
	App                  string   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	QueueId              string   `protobuf:"bytes,2,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	Job                  *Job     `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobUpdate) Reset()         { *m = JobUpdate{} }
func (m *JobUpdate) String() string { return proto.CompactTextString(m) }
func (*JobUpdate) ProtoMessage()    {}
func (*JobUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_summary_741b49c5a0045d04, []int{1}
}
func (m *JobUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobUpdate.Unmarshal(m, b)
}
func (m *JobUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobUpdate.Marshal(b, m, deterministic)
}
func (dst *JobUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobUpdate.Merge(dst, src)
}
func (m *JobUpdate) XXX_Size() int {
	return xxx_messageInfo_JobUpdate.Size(m)
}
func (m *JobUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_JobUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_JobUpdate proto.InternalMessageInfo

func (m *JobUpdate) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *JobUpdate) GetQueueId() string {
	if m != nil {
		return m.QueueId
	}
	return ""
}

func (m *JobUpdate) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type JobBlueprint struct {
	JobName              string            `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Fields               map[string]string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *JobBlueprint) Reset()         { *m = JobBlueprint{} }
func (m *JobBlueprint) String() string { return proto.CompactTextString(m) }
func (*JobBlueprint) ProtoMessage()    {}
func (*JobBlueprint) Descriptor() ([]byte, []int) {
	return fileDescriptor_summary_741b49c5a0045d04, []int{2}
}
func (m *JobBlueprint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobBlueprint.Unmarshal(m, b)
}
func (m *JobBlueprint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobBlueprint.Marshal(b, m, deterministic)
}
func (dst *JobBlueprint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobBlueprint.Merge(dst, src)
}
func (m *JobBlueprint) XXX_Size() int {
	return xxx_messageInfo_JobBlueprint.Size(m)
}
func (m *JobBlueprint) XXX_DiscardUnknown() {
	xxx_messageInfo_JobBlueprint.DiscardUnknown(m)
}

var xxx_messageInfo_JobBlueprint proto.InternalMessageInfo

func (m *JobBlueprint) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *JobBlueprint) GetFields() map[string]string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Stats struct {
	App                  string          `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	QueueId              string          `protobuf:"bytes,2,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	Jobs                 map[string]*Job `protobuf:"bytes,3,rep,name=jobs,proto3" json:"jobs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ActiveJobs           uint32          `protobuf:"varint,4,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	QueuedJobs           uint32          `protobuf:"varint,5,opt,name=queued_jobs,json=queuedJobs,proto3" json:"queued_jobs,omitempty"`
	ProcessedJobs        uint32          `protobuf:"varint,6,opt,name=processed_jobs,json=processedJobs,proto3" json:"processed_jobs,omitempty"`
	DeferredJobs         uint32          `protobuf:"varint,7,opt,name=deferred_jobs,json=deferredJobs,proto3" json:"deferred_jobs,omitempty"`
	FailedJobs           uint32          `protobuf:"varint,8,opt,name=failed_jobs,json=failedJobs,proto3" json:"failed_jobs,omitempty"`
	RequeuedJobs         uint32          `protobuf:"varint,9,opt,name=requeued_jobs,json=requeuedJobs,proto3" json:"requeued_jobs,omitempty"`
	JobBlueprints        []*JobBlueprint `protobuf:"bytes,10,rep,name=job_blueprints,json=jobBlueprints,proto3" json:"job_blueprints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_summary_741b49c5a0045d04, []int{3}
}
func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (dst *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(dst, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *Stats) GetQueueId() string {
	if m != nil {
		return m.QueueId
	}
	return ""
}

func (m *Stats) GetJobs() map[string]*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *Stats) GetActiveJobs() uint32 {
	if m != nil {
		return m.ActiveJobs
	}
	return 0
}

func (m *Stats) GetQueuedJobs() uint32 {
	if m != nil {
		return m.QueuedJobs
	}
	return 0
}

func (m *Stats) GetProcessedJobs() uint32 {
	if m != nil {
		return m.ProcessedJobs
	}
	return 0
}

func (m *Stats) GetDeferredJobs() uint32 {
	if m != nil {
		return m.DeferredJobs
	}
	return 0
}

func (m *Stats) GetFailedJobs() uint32 {
	if m != nil {
		return m.FailedJobs
	}
	return 0
}

func (m *Stats) GetRequeuedJobs() uint32 {
	if m != nil {
		return m.RequeuedJobs
	}
	return 0
}

func (m *Stats) GetJobBlueprints() []*JobBlueprint {
	if m != nil {
		return m.JobBlueprints
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterType((*JobUpdate)(nil), "JobUpdate")
	proto.RegisterType((*JobBlueprint)(nil), "JobBlueprint")
	proto.RegisterMapType((map[string]string)(nil), "JobBlueprint.FieldsEntry")
	proto.RegisterType((*Stats)(nil), "Stats")
	proto.RegisterMapType((map[string]*Job)(nil), "Stats.JobsEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SummaryClient is the client API for Summary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SummaryClient interface {
	UpdateStats(ctx context.Context, in *Stats, opts ...grpc.CallOption) (*Stats, error)
	UpdateJob(ctx context.Context, in *JobUpdate, opts ...grpc.CallOption) (*Job, error)
}

type summaryClient struct {
	cc *grpc.ClientConn
}

func NewSummaryClient(cc *grpc.ClientConn) SummaryClient {
	return &summaryClient{cc}
}

func (c *summaryClient) UpdateStats(ctx context.Context, in *Stats, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/Summary/UpdateStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summaryClient) UpdateJob(ctx context.Context, in *JobUpdate, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := c.cc.Invoke(ctx, "/Summary/UpdateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SummaryServer is the server API for Summary service.
type SummaryServer interface {
	UpdateStats(context.Context, *Stats) (*Stats, error)
	UpdateJob(context.Context, *JobUpdate) (*Job, error)
}

func RegisterSummaryServer(s *grpc.Server, srv SummaryServer) {
	s.RegisterService(&_Summary_serviceDesc, srv)
}

func _Summary_UpdateStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).UpdateStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Summary/UpdateStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).UpdateStats(ctx, req.(*Stats))
	}
	return interceptor(ctx, in, info, handler)
}

func _Summary_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Summary/UpdateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).UpdateJob(ctx, req.(*JobUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

var _Summary_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Summary",
	HandlerType: (*SummaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateStats",
			Handler:    _Summary_UpdateStats_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _Summary_UpdateJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "summary/summary.proto",
}

func init() { proto.RegisterFile("summary/summary.proto", fileDescriptor_summary_741b49c5a0045d04) }

var fileDescriptor_summary_741b49c5a0045d04 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xb7, 0x49, 0x9b, 0x6e, 0xa7, 0x9b, 0x6a, 0x65, 0xc1, 0x2a, 0x9b, 0xcb, 0xae, 0x02,
	0x48, 0x7b, 0x0a, 0xa2, 0x70, 0x00, 0x24, 0x2e, 0x48, 0x20, 0x11, 0x24, 0x84, 0xb2, 0x42, 0x1c,
	0x2b, 0x7b, 0xed, 0xa2, 0xa4, 0x7f, 0x1c, 0x6c, 0x67, 0x51, 0x9f, 0x84, 0x07, 0xe0, 0x45, 0x91,
	0xc7, 0x76, 0x09, 0x07, 0x0e, 0x9c, 0x92, 0xf9, 0xf2, 0xcb, 0x37, 0xe3, 0x99, 0x31, 0x3c, 0xd4,
	0xfd, 0x6e, 0x47, 0xd5, 0xe1, 0xa9, 0x7f, 0x96, 0x9d, 0x92, 0x46, 0x16, 0x5f, 0x21, 0xae, 0x24,
	0x23, 0x0b, 0x88, 0x1a, 0x9e, 0x8d, 0xae, 0x47, 0x37, 0xb3, 0x3a, 0x6a, 0x38, 0x39, 0x87, 0xd8,
	0xd0, 0x6f, 0x59, 0x84, 0x82, 0x7d, 0x25, 0x17, 0x90, 0x68, 0x43, 0x4d, 0xaf, 0xb3, 0x18, 0x45,
	0x1f, 0x59, 0xfd, 0x87, 0x54, 0x1b, 0xa1, 0xb2, 0xb1, 0xd3, 0x5d, 0x54, 0x7c, 0x86, 0x59, 0x25,
	0xd9, 0x97, 0x8e, 0x53, 0x23, 0xac, 0x1d, 0xed, 0x3a, 0xef, 0x6f, 0x5f, 0xc9, 0x25, 0x9c, 0x7e,
	0xef, 0x45, 0x2f, 0x56, 0x0d, 0xf7, 0x59, 0xa6, 0x18, 0x7f, 0xe0, 0xe4, 0x02, 0xe2, 0x56, 0x32,
	0x4c, 0x33, 0x5f, 0x8e, 0xcb, 0x4a, 0xb2, 0xda, 0x0a, 0xc5, 0xcf, 0x11, 0x9c, 0x55, 0x92, 0xbd,
	0xdd, 0xf6, 0xa2, 0x53, 0xcd, 0xde, 0x58, 0x8f, 0x56, 0xb2, 0xd5, 0x9e, 0xee, 0x84, 0xb7, 0x9e,
	0xb6, 0x92, 0x7d, 0xa2, 0x3b, 0x41, 0x9e, 0x41, 0xb2, 0x6e, 0xc4, 0x96, 0xeb, 0x2c, 0xba, 0x8e,
	0x6f, 0xe6, 0xcb, 0xcb, 0x72, 0xf8, 0x67, 0xf9, 0x1e, 0xbf, 0xbd, 0xdb, 0x1b, 0x75, 0xa8, 0x3d,
	0x98, 0xbf, 0x82, 0xf9, 0x40, 0xb6, 0x25, 0x6f, 0xc4, 0x21, 0x94, 0xbc, 0x11, 0x07, 0xf2, 0x00,
	0x26, 0xf7, 0x74, 0xdb, 0x0b, 0x5f, 0xaf, 0x0b, 0x5e, 0x47, 0x2f, 0x47, 0xc5, 0xaf, 0x18, 0x26,
	0xb7, 0x86, 0x1a, 0xfd, 0x7f, 0x07, 0x7d, 0x0c, 0xe3, 0x56, 0x32, 0xdb, 0x50, 0x5b, 0xe2, 0x79,
	0x89, 0x16, 0xb6, 0x50, 0x5f, 0x19, 0x7e, 0x25, 0x57, 0x30, 0xa7, 0x77, 0xa6, 0xb9, 0x17, 0x2b,
	0x84, 0x6d, 0x97, 0xd3, 0x1a, 0x9c, 0x54, 0x79, 0x00, 0x1d, 0xb9, 0x03, 0x26, 0x0e, 0x70, 0x12,
	0x02, 0x4f, 0x60, 0xd1, 0x29, 0x79, 0x27, 0xb4, 0x0e, 0x4c, 0x82, 0x4c, 0x7a, 0x54, 0x11, 0x7b,
	0x04, 0x29, 0x17, 0x6b, 0xa1, 0x54, 0xa0, 0xa6, 0x48, 0x9d, 0x05, 0x31, 0x24, 0x5b, 0xd3, 0x66,
	0x1b, 0x90, 0x53, 0x97, 0xcc, 0x49, 0xc1, 0x45, 0x89, 0x61, 0x3d, 0x33, 0xe7, 0x12, 0x44, 0x84,
	0x5e, 0xc0, 0xc2, 0x4e, 0x8e, 0x85, 0x81, 0xe8, 0x0c, 0xb0, 0x07, 0xe9, 0x5f, 0x63, 0xaa, 0xd3,
	0x76, 0x10, 0xe9, 0xfc, 0x0d, 0xae, 0xd4, 0x3f, 0xe7, 0x93, 0x0f, 0xe7, 0x13, 0x36, 0xe7, 0xcf,
	0x94, 0x96, 0x1f, 0x61, 0x7a, 0xeb, 0x76, 0xdf, 0x9e, 0xc2, 0x6d, 0xa6, 0x9b, 0x5a, 0xe2, 0x5a,
	0x9f, 0xfb, 0x67, 0x71, 0x42, 0xae, 0x60, 0xe6, 0x00, 0x7b, 0x39, 0xa0, 0x3c, 0x6e, 0x72, 0x8e,
	0xae, 0xc5, 0x09, 0x4b, 0xf0, 0xfa, 0x3c, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x48, 0xd9, 0xcf,
	0x5f, 0x57, 0x03, 0x00, 0x00,
}
