// Code generated by protoc-gen-go.
// source: summary.proto
// DO NOT EDIT!

/*
Package summary is a generated protocol buffer package.

It is generated from these files:
	summary.proto

It has these top-level messages:
	Job
	Stats
*/
package summary

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Job struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Tag    string `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	Worker string `protobuf:"bytes,4,opt,name=worker" json:"worker,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Job) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Job) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

type Stats struct {
	App           string          `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	QueueId       string          `protobuf:"bytes,2,opt,name=queue_id,json=queueId" json:"queue_id,omitempty"`
	Jobs          map[string]*Job `protobuf:"bytes,3,rep,name=jobs" json:"jobs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ActiveJobs    uint32          `protobuf:"varint,4,opt,name=active_jobs,json=activeJobs" json:"active_jobs,omitempty"`
	QueuedJobs    uint32          `protobuf:"varint,5,opt,name=queued_jobs,json=queuedJobs" json:"queued_jobs,omitempty"`
	ProcessedJobs uint32          `protobuf:"varint,6,opt,name=processed_jobs,json=processedJobs" json:"processed_jobs,omitempty"`
	DeferredJobs  uint32          `protobuf:"varint,7,opt,name=deferred_jobs,json=deferredJobs" json:"deferred_jobs,omitempty"`
	FailedJobs    uint32          `protobuf:"varint,8,opt,name=failed_jobs,json=failedJobs" json:"failed_jobs,omitempty"`
	RequeuedJobs  uint32          `protobuf:"varint,9,opt,name=requeued_jobs,json=requeuedJobs" json:"requeued_jobs,omitempty"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Stats) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *Stats) GetQueueId() string {
	if m != nil {
		return m.QueueId
	}
	return ""
}

func (m *Stats) GetJobs() map[string]*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *Stats) GetActiveJobs() uint32 {
	if m != nil {
		return m.ActiveJobs
	}
	return 0
}

func (m *Stats) GetQueuedJobs() uint32 {
	if m != nil {
		return m.QueuedJobs
	}
	return 0
}

func (m *Stats) GetProcessedJobs() uint32 {
	if m != nil {
		return m.ProcessedJobs
	}
	return 0
}

func (m *Stats) GetDeferredJobs() uint32 {
	if m != nil {
		return m.DeferredJobs
	}
	return 0
}

func (m *Stats) GetFailedJobs() uint32 {
	if m != nil {
		return m.FailedJobs
	}
	return 0
}

func (m *Stats) GetRequeuedJobs() uint32 {
	if m != nil {
		return m.RequeuedJobs
	}
	return 0
}

func init() {
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterType((*Stats)(nil), "Stats")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Summary service

type SummaryClient interface {
	UpdateStats(ctx context.Context, in *Stats, opts ...grpc.CallOption) (*Stats, error)
}

type summaryClient struct {
	cc *grpc.ClientConn
}

func NewSummaryClient(cc *grpc.ClientConn) SummaryClient {
	return &summaryClient{cc}
}

func (c *summaryClient) UpdateStats(ctx context.Context, in *Stats, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := grpc.Invoke(ctx, "/Summary/UpdateStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Summary service

type SummaryServer interface {
	UpdateStats(context.Context, *Stats) (*Stats, error)
}

func RegisterSummaryServer(s *grpc.Server, srv SummaryServer) {
	s.RegisterService(&_Summary_serviceDesc, srv)
}

func _Summary_UpdateStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryServer).UpdateStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Summary/UpdateStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryServer).UpdateStats(ctx, req.(*Stats))
	}
	return interceptor(ctx, in, info, handler)
}

var _Summary_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Summary",
	HandlerType: (*SummaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateStats",
			Handler:    _Summary_UpdateStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "summary.proto",
}

func init() { proto.RegisterFile("summary.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x65, 0x83, 0x01, 0x0f, 0x47, 0x48, 0x0f, 0x66, 0x72, 0xd1, 0xa0, 0x26, 0xc4, 0x03,
	0x87, 0x79, 0x31, 0x26, 0x1e, 0x3d, 0xb8, 0xe3, 0x88, 0xf1, 0x48, 0x3a, 0x5a, 0xcc, 0x1c, 0xd8,
	0xd9, 0x76, 0x98, 0x7d, 0x68, 0xbf, 0x83, 0xe9, 0x7b, 0x2b, 0xf1, 0x44, 0xdf, 0x8f, 0x5f, 0xfe,
	0xaf, 0xfb, 0x17, 0x62, 0xd3, 0x1c, 0x0e, 0x5c, 0xb7, 0xab, 0x5a, 0x2b, 0xab, 0x16, 0xef, 0x10,
	0x66, 0xaa, 0x60, 0x53, 0x08, 0x4a, 0x91, 0xf4, 0xae, 0x7b, 0xcb, 0x71, 0x1e, 0x94, 0x82, 0xcd,
	0x20, 0xb4, 0xfc, 0x23, 0x09, 0x10, 0xb8, 0x23, 0xbb, 0x80, 0xc8, 0x58, 0x6e, 0x1b, 0x93, 0x84,
	0x08, 0xbb, 0xc9, 0xf1, 0x1f, 0xa5, 0x2b, 0xa9, 0x93, 0x3e, 0x71, 0x9a, 0x16, 0xbf, 0x01, 0x0c,
	0xd6, 0x96, 0x5b, 0xe3, 0xb2, 0x78, 0x5d, 0x77, 0xe1, 0xee, 0xc8, 0x2e, 0x61, 0xf4, 0xdd, 0xc8,
	0x46, 0x6e, 0x4a, 0xd1, 0xad, 0x18, 0xe2, 0xfc, 0x2a, 0xd8, 0x2d, 0xf4, 0x3f, 0x55, 0xe1, 0x96,
	0x84, 0xcb, 0x49, 0x3a, 0x5b, 0x61, 0xc4, 0x2a, 0x53, 0x85, 0x79, 0xf9, 0xb2, 0xba, 0xcd, 0xf1,
	0x5f, 0x76, 0x05, 0x13, 0xbe, 0xb5, 0xe5, 0x51, 0x6e, 0x50, 0x76, 0x9b, 0xe3, 0x1c, 0x08, 0x65,
	0x9d, 0x80, 0x89, 0x82, 0x84, 0x01, 0x09, 0x84, 0x50, 0xb8, 0x83, 0x69, 0xad, 0xd5, 0x56, 0x1a,
	0xe3, 0x9d, 0x08, 0x9d, 0xf8, 0x44, 0x51, 0xbb, 0x81, 0x58, 0xc8, 0x9d, 0xd4, 0xda, 0x5b, 0x43,
	0xb4, 0xce, 0x3d, 0xf4, 0xcb, 0x76, 0xbc, 0xdc, 0x7b, 0x65, 0x44, 0xcb, 0x08, 0xf9, 0x14, 0x2d,
	0xff, 0xdf, 0x67, 0x4c, 0x29, 0x1e, 0x3a, 0x69, 0xfe, 0x0c, 0xe3, 0xd3, 0x67, 0xba, 0xce, 0x2a,
	0xd9, 0xfa, 0xce, 0x2a, 0xd9, 0xb2, 0x39, 0x0c, 0x8e, 0x7c, 0xdf, 0x48, 0x2c, 0x6c, 0x92, 0xf6,
	0x5d, 0x27, 0x39, 0xa1, 0xa7, 0xe0, 0xb1, 0x97, 0xde, 0xc3, 0x70, 0x4d, 0x2f, 0xeb, 0xee, 0xf3,
	0x56, 0x0b, 0x6e, 0x25, 0xf5, 0x1f, 0x51, 0x89, 0xf3, 0xee, 0x77, 0x71, 0x56, 0x44, 0xf8, 0xf6,
	0x0f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x46, 0x40, 0x39, 0x0c, 0x02, 0x00, 0x00,
}
